   void validateDuplicateMerchantUserOnUpdate(String userName, String email, String mobilePhone) {
        List<String> dbUserName = merchantUserDao.getUserNameByEmailOrMobilePhone(email, mobilePhone);
        boolean found = dbUserName.stream().allMatch(u -> u.equalsIgnoreCase(userName));
        if (!found) {
            errorDtoList.add(ErrorDto.builder().errorCode(ErrorConstants.ALREADY_EXIST_ERROR_CODE).errorMessage(MessageFormat.format(USER_ALREADY_EXIST_ERROR_MESSAGE_UPDATE, email, mobilePhone)).build());
            throwIfErrors();
        }
    }

    @Test
    public void testValidateDuplicateMerchantUserOnUpdateElse()
    {   List<String> dbUserName=List.of("s","d");
        when(merchantUserDao.getUserNameByEmailOrMobilePhone("kk@test.com", "7026491458")).thenReturn(dbUserName);

        
        ValidationException exception = assertThrows(ValidationException.class, () ->   merchantUserValidator.validateDuplicateMerchantUserOnUpdate("gfydrt","sh@gmail.com","9827785643 "));
        assertEquals(exception.getErrorMessages().getFirst().getErrorCode(),"7004");
    }

not getting executed validateDuplicateMerchantUserOnUpdate because of found 
